version: '3.8'
services:
  database:
    image: 'postgres:15.2-alpine'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "54321:5432"
    volumes:
      - "./.docker/database:/var/lib/postgresql/data"
